language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7

before_script:
  - chmod +x gradlew

script:
  - ./gradlew test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)